# Generated by Django 5.2.4 on 2025-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_swap', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills_offered',
            field=models.ManyToManyField(blank=True, related_name='offered_by', to='skill_swap.skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills_wanted',
            field=models.ManyToManyField(blank=True, related_name='wanted_by', to='skill_swap.skill'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
