# Generated by Django 5.2.4 on 2025-07-12 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_swap', '0003_alter_userprofile_skills_offered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swaprequest',
            old_name='sender',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='swaprequest',
            old_name='receiver',
            new_name='to_user',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='skill_offered',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='skill_wanted',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='status',
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='offered_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_swaps', to='skill_swap.skill'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requested_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_swaps', to='skill_swap.skill'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='swap',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='skill_swap.swaprequest'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('weekends', 'Weekends'), ('evenings', 'Evenings'), ('weekdays', 'Weekdays'), ('anytime', 'Anytime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
